name: Deploy Frontend to Hetzner

on:
  push:
    branches: ['master'] # o 'main' si cambias

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # 1) Limpia TODO el target (incluidos restos ocultos)
      - name: Clean target folder
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/code4ce/erp/frontend
            shopt -s dotglob nullglob
            rm -rf /var/www/code4ce/erp/frontend/*

      # 2) Sube SOLO el contenido de dist (no la carpeta dist)
      - name: Upload dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'dist/*'
          target: '/var/www/code4ce/erp/frontend'

      # 3) Verifica que index.html quedó en el root (debug útil)
      - name: Verify deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls -la /var/www/code4ce/erp/frontend
            test -f /var/www/code4ce/erp/frontend/index.html && echo "✅ index.html found" || (echo "❌ index.html NOT FOUND" && exit 1)

      # 4) (Opcional) Recargar Nginx si lo necesitas.
      # Quita este paso si no tienes sudo sin password configurado.
      # - name: Reload Nginx
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       sudo -n nginx -t && sudo -n systemctl reload nginx
