name: Deploy Frontend to Hetzner

on:
  push:
    branches: ['master'] # cambia si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # Limpia la carpeta remota para evitar archivos viejos
      - name: Clean target folder
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /var/www/code4ce/erp/frontend
            rm -rf /var/www/code4ce/erp/frontend/*

      # Sube el build (dist/*) a la carpeta remota
      - name: Upload dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'dist/*'
          target: '/var/www/code4ce/erp/frontend'
